# ubuntu environment (18.04)
dist: xenial

# golang
language: go

# Go version
go:
  - 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

# Dependencies
before_install:
  - go get -v github.com/fatih/color
  - go get -v github.com/olekukonko/tablewriter
  - go get -v github.com/common-nighthawk/go-figure
  - go get -v github.com/carmark/pseudo-terminal-go/terminal