# Ubuntu environment (18.04)
dist: xenial

# Golang
language: go

# Go version
go:
  - 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

# Dependencies
before_install:
  - go get -d ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)